apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: htto-go-ingress
spec:
  rules:
  - host: young-dev.com     
    http:
      paths:
      - path: /
        backend:
          serviceName: http-go-svc
          servicePort: 80
