apiVersion: v1
kind: Pod
metadata:
  name: hostpath-httpd
spec:
  containers:
  # webserver
  - image: httpd
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/local/apache2/htdocs
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    hostPath:
        path: /var/htdocs
        type: Directory
