---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
  namespace: prometheus
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus
    component: server
  type: NodePort

