apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-mysql
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "godo1234"
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql
  volumes:
  - name: mysql
    persistentVolumeClaim:
      claimName: mysql-pvc
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: storage-mysql
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
