apiVersion: v1
data:
  zabbix-alert.sh: |
    #!/bin/sh

    webhook_url=$1
    sendto=$2
    subject=$3
    message=$4

    curl -d '{"zabbix_subject": "'"${subject}"'", "zabbix_message": "'"${message}"'"}' -H "Content-Type: application/json" -X POST http://10.128.128.139:10514

kind: ConfigMap
metadata:
  labels:
    app: zabbix-zabbix-server
  name: zabbix-alert
  namespace: zabbix
