apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: zabbix
    meta.helm.sh/release-namespace: zabbix
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-name: EKS-ZABBIX-SERVER
  labels:
    app: zabbix-zabbix-server
    app.kubernetes.io/instance: zabbix-zabbix-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: zabbix-server
    helm.sh/chart: zabbix-1.0.0
  name: zabbix-zabbix-server
  namespace: zabbix
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: zabbix-server
    port: 10051
    protocol: TCP
    targetPort: 10051
  selector:
    app: zabbix-zabbix-server
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
